services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: API/WebAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=85.202.192.76;Port=5432;Database=eduLabDb;Username=auyl_user;Password=auyl_password
      - Minio__Endpoint=85.202.192.76:9000
      - Minio__AccessKey=gv3IohIp2G1k84OzCMRJ
      - Minio__SecretKey=4eB8jLySR7mDdvMvIJDfSSVoYAxMrYBN9MvgN28u
      - Minio__DefaultBucket=course
      - Minio__UseSSL=false
      - JwtSettings__Secret=This is a secret key for jwt token generation and validation process
      - JwtSettings__Issuer=http://localhost:5000
      - JwtSettings__Audience=http://localhost:5000
      - JwtSettings__ExpirationInMinutes=60
      - JwtSettings__RefreshTokenExpirationInDays=7
