services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: API/WebAPI/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=minio_admin
      - Minio__SecretKey=12345678
      - Minio__BucketName=course
      - Minio__UseSSL=false
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

volumes:
  minio_data: