services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: API/WebAPI/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=123456;Database=edu_lab_db
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=minio_admin
      - Minio__SecretKey=12345678
      - Minio__BucketName=course
      - Minio__UseSSL=false
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: edu_lab_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data: